<?php

use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\Http\RequestHandlers\AddNewFact;
use Fisharebest\Webtrees\Http\RequestHandlers\SelectNewFact;
use Fisharebest\Webtrees\I18N;
use Ramsey\Uuid\Uuid;

/**
 * @var array<string,string> $add_facts
 * @var array<string,string> $quick_facts
 * @var GedcomRecord         $record
 */

  //[RC] added for issue #49
  $disambiguator = Uuid::uuid4()->toString();
?>

<tr>
    <th scope="row">
        <label for="add-fact<?= $disambiguator ?>">
            <?= I18N::translate('Fact or event') ?>
        </label>
    </th>
    <td>

        <form method="post" action="<?= e(route(SelectNewFact::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref()])) ?>" onsubmit="if ($('#add-fact<?= $disambiguator ?>').val() === null) {event.preventDefault();}">

            <div class="input-group">
                <select class="custom-select" id="add-fact<?= $disambiguator ?>" name="fact">
                    <option value="" disabled="disabled" selected="selected">
                        <?= I18N::translate('&lt;select&gt;') ?>
                    </option>
                    <?php foreach ($add_facts as $fact => $label) : ?>
                        <option value="<?= $fact ?>"><?= $label ?></option>
                    <?php endforeach ?>
                </select>
                <button class="btn btn-light" type="submit">
                    <?= /* I18N: A button label. */ I18N::translate('add') ?>
                </button>
            </div>
            <?= csrf_field() ?>
        </form>

        <div class="wt-quick-facts">
            <?php foreach ($quick_facts as $fact => $label) : ?>
                <a class="btn btn-link btn-sm wt-quick-fact" href="<?= e(route(AddNewFact::class, [
                    'fact' => $fact,
                    'xref' => $record->xref(),
                    'tree' => $record->tree()->name(),
                ])) ?>">
                    <?= $label ?>
                </a>
            <?php endforeach ?>
        </div>
    </td>
</tr>
