.wt-icon-mapire-eu-maps {
  /* mapire-eu.png embedded via https://onlineimagetools.com/convert-image-to-data-uri */
  content: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5AELDw0wM0tUWQAAANFJREFUOMulk68KAkEQxn+od0XkMIiC1WwRLIKa7hksZn0AfQiDZoNFMBl8CYNVwaKIYPMJDIJ/yoRhYd29c2DY2dnv+2Z2lgW7VYEpUCSFtYCP+BOo2IAZYz8DQiCrcgFwl3j8q+pCKu5V5avq5Czr3CaQF9AOqBtnXeAEbH1n0FeVH0CcZIBrRdY+9CHngLcQLkAPuCmR0CXQUOBAcrHKNV0CBQVeAhGwUbmyzzUOivBS8cp3iDXLEEtJXmJikEdJ/0Kk2j+S0joi0OYPG7gAX8KcQbEX5O8GAAAAAElFTkSuQmCC);
}

<?php
  //cannot just use content:url because we may have to resize
  //have to use empty content:url(); to prevent showing fa icon
  //what a mess
?>
.wt-icon-custom-map-provider-1 {
  background-image: url(<?= $module->getPreference('CMP_1_ICON_DATA_URI', '') ?>);
  background-size: 16px 16px;
  background-repeat: no-repeat;
  display: inline-block;
  width: 16px;
  height: 16px;
  content:url();
}
